<a href="https://colab.research.google.com/github/MariaCarolinass/analise-de-dados/blob/main/tarefas/matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Operações Algébricas em Matrizes

Implemente um conjunto de operações algébricas em matrizes utilizando NumPy. O objetivo é consolidar o entendimento de multiplicação, adição, transposição, inversão de matrizes e cálculo de determinantes.

Importando o Numpy:

In [1]:
import numpy as np

## Geração das Matrizes:

In [49]:
# matriz A
A = np.array(np.random.randint(1, 10, size=(3, 3)))
print("Matriz A:")
print(A)

# matriz B
B = np.array(np.random.randint(1, 10, size=(3, 3)))
print("\nMatriz B:")
print(B)

Matriz A:
[[1 8 4]
 [1 4 5]
 [6 3 4]]

Matriz B:
[[5 8 7]
 [2 1 7]
 [8 6 7]]


## Operações Algébricas:

Soma das matrizes:

In [50]:
soma = A + B
print(soma)

[[ 6 16 11]
 [ 3  5 12]
 [14  9 11]]


Produto das matrizes:

In [51]:
produto = np.dot(A, B) # ou produto = A @ B
print(produto)

[[53 40 91]
 [53 42 70]
 [68 75 91]]


Transposição:

In [52]:
transposta_produto = np.transpose(produto) # ou produto.T
print(transposta_produto)

[[53 53 68]
 [40 42 75]
 [91 70 91]]


Determinante:

In [53]:
det_produto = np.linalg.det(produto)
print(det_produto)

23624.999999999993


Inversão de matriz:

In [54]:
if det_produto == 0:
  print("A matriz não é inversível.")
else:
  inversa_produto = np.linalg.inv(produto)
  print(inversa_produto)

[[-0.06044444  0.13481481 -0.04325926]
 [-0.00266667 -0.05777778  0.04711111]
 [ 0.04736508 -0.05312169  0.00448677]]
